name: jcc_admin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  go_router: ^11.1.3

    #  UI Libs
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  #  Bloc Libs
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  syncfusion_flutter_gauges: ^23.1.42
  fl_chart: ^0.64.0
  form_bloc: ^0.31.0

  #  Firebase lib
  firebase_core:
  cloud_firestore:
  intl:
  firebase_auth:
  flutter_form_bloc: ^0.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/lottie/
    - assets/artworks/
    - assets/backgrounds/
    - assets/complaint_data/
    - assets/departmentIcons/
    - assets/departmentThumbnail/


